name: first workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: window-latest
    steps:
      - name: Print greeting
        run: echo "hello world"
      - name: Print goodbye
        run: echo "done-goodby"
