name: first workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: windows-latest
    steps:
      - name: checking eslint
        run: npx eslint .
      - name: Print goodbye
        run: echo "done-goodbye"
